#!/bin/bash

########## Arch Linux ##########

######### Debian ##########

cd prereqs/boost_1_54_0
./bootstrap.sh
./bjam architecture=x86 address-model=64 threading=multi --with-program_options --with-thread --with-filesystem --with-chrono --with-system --with-regex --with-test --with-date_time --with-coroutine --with-atomic --with-math --with-graph --with-exception -sBUILD=boost_unit_test_framework -j4
sudo ./b2 install --prefix=/usr/local/ cxxflags="--std=c++11 -I/usr/include/python2.7/"

sudo mkdir -p /opt/bitgrinder/data/config

LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
export LD_LIBRARY_PATH

# create bitgrinder user
# chown bitgrinder
