#!/bin/bash
git clone https://github.com/akumuli.akumuli.git
git clone https://github.com/prometheus/prometheus.git
git clone https://github.com/jupp0r/prometheus-cpp.git

########## Arch Linux ##########
# Akumuli Prereqs
# sudo pacman -S jemalloc libmicrohttpd apr sqlite cmake
## sudo pacman -S boost boostlibs jemalloc libmicrohttpd apr sqlite cmake
# wget https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.7z
# sudo apacman -S log4cxx
# wget http://mirror.reverse.net/pub/apache/logging/log4cxx/0.10.0/apache-log4cxx-0.10.0.tar.gz

